const workflowData = [
  {"id":	"1",	"workflowTitle":	"Pricing Provisional Sums",	"action":	false},
  {"id":	"2",	"workflowTitle":	"Submission of Contractor's Securities",	"action":	false},
  {"id":	"3",	"workflowTitle":	"Submission of Principal's Securities",	"action":	false},
  {"id":	"4",	"workflowTitle":	"Financial recourse using Securities",	"action":	false},
  {"id":	"5",	"workflowTitle":	"Swapping or changing securities",	"action":	false},
  {"id":	"6",	"workflowTitle":	"Reducing and releasing security at Practical Completion",	"action":	false},
  {"id":	"7",	"workflowTitle":	"Reducing Contractor's security for plant and materials that have been provided",	"action":	false},
  {"id":	"8",	"workflowTitle":	"Providing a Deed of Guarantee",	"action":	false},
  {"id":	"9",	"workflowTitle":	"Notifying of a Discrepancy in the Documentation",	"action":	false},
  {"id":	"10",	"workflowTitle":	"Principal's Supply of Documents",	"action":	false},
  {"id":	"11",	"workflowTitle":	"Contractor Providing documents to the Superintendent",	"action":	false},
  {"id":	"12",	"workflowTitle":	"Superintendent's response to documents provided by the Contractor",	"action":	false},
  {"id":	"13",	"workflowTitle":	"Contractor's request for approval to disclose project information to the media",	"action":	false},
  {"id":	"14",	"workflowTitle":	"Contractor requests the Superintendent's approval to subcontract work",	"action":	false},
  {"id":	"15",	"workflowTitle":	"Superintendent's decision in respect of subcontracting of work by the Contractor",	"action":	false},
  {"id":	"16",	"workflowTitle":	"Contractor's notice of a change in Legislative Requirements",	"action":	false},
  {"id":	"17",	"workflowTitle":	"Superintendent's assessment of legislative change",	"action":	false},
  {"id":	"18",	"workflowTitle":	"Excepted risks and reinstatement notification",	"action":	false},
  {"id":	"19",	"workflowTitle":	"Contractor's provision of insurances",	"action":	false},
  {"id":	"20",	"workflowTitle":	"Potential claims against insurances and settlement",	"action":	false},
  {"id":	"21",	"workflowTitle":	"Superintendent delegation of representative",	"action":	false},
  {"id":	"22",	"workflowTitle":	"Contractor's representative",	"action":	false},
  {"id":	"23",	"workflowTitle":	"Notice of site possession to the Contractor",	"action":	false},
  {"id":	"24",	"workflowTitle":	"Discovery of latent conditions",	"action":	false},
  {"id":	"25",	"workflowTitle":	"Quality System",	"action":	false},
  {"id":	"26",	"workflowTitle":	"Defect notification and rectification",	"action":	false},
  {"id":	"27",	"workflowTitle":	"Superintendent directs a change to the Program",	"action":	false},
  {"id":	"28",	"workflowTitle":	"Superintendent suspends Work",	"action":	false},
  {"id":	"29",	"workflowTitle":	"Delays to the Work (EOTs)",	"action":	false},
  {"id":	"30",	"workflowTitle":	"Achieving Practical Completion",	"action":	false},
  {"id":	"31",	"workflowTitle":	"Directing a Variation as the Superintendent",	"action":	false},
  {"id":	"32",	"workflowTitle":	"Superintendent considering a Variation",	"action":	false},
  {"id":	"33",	"workflowTitle":	"Contractor's request to vary the work for convenience",	"action":	false},
  {"id":	"34",	"workflowTitle":	"Contractor's notice of a cost resulting from a direction or request",	"action":	false},
  {"id":	"35",	"workflowTitle":	"Payment made to the Contractor",	"action":	true}
]

export default workflowData;
